guyfedwards/nom

cmd/nom/main.go
go.mod
go.sum

I could not find/download the 1.5.0 version of the go-flags package. It's not available at https://github.com/jessevdk/go-flags/releases

handle errors in fewer places, use version 1.4.0 for the go-flags package

---

cmd/nom/main.go

Setting the env var explicitly is the cleanest way to have all child
packages respect the client and keep it in the code rather than a build
flag.
closes #7

fix: disable http2 client for requests

---

internal/config/main.go

A quick fix to make the `nom add` command not permit duplicate URLs in `config.yml`, this fixes #26

fix: duplicate feed entries are now disallowed

---

cmd/nom/main.go
internal/commands/main.go
internal/config/main.go
internal/config/main_test.go

Hey there!
This deals with issue #13 
The proposed solution is to add a `--preview` flag, but I find it unnecessary as
```
nom <URL>
```
feels like a more straightforward interface since we can check if `args[0]` is a URL or not and as such distinguish vs commands
idk if it's a good solution, I have 0 experience with go and 0 experience contributing to open source projects. But I was looking forward to make my first one not only to learn go, but contribute to something that I actually looking to use (long time newsboat user) and a feature to preview a feed looked like a nice opportunity as it was something I was missing in newsboat.
The solution doesn't use cache, and as such a little slow on transitions, - maybe a short-lived in-memory cache can be implemented here. 
Code review is very …

Add option to view feed without loading feeds from a config

---

cmd/nom/main.go
internal/cache/file.go
internal/cache/file_test.go
internal/cache/main.go
internal/cache/memory.go
internal/commands/main.go
internal/config/main_test.go

A proposed solution for #30
It allows not to make unnecessary HTTP calls on pretty much any user interaction with the TUI.
I was worried if we implement file cache in temporary files with generated names, we are risking leaving those temp files dangling if the program exits inappropriately (segmentation faults, SIGKILL'ed, etc) and as such doesn't perform proper cleanup (i.e. never gets to the point when it does the deferred `cleaupTemporaryCacheFile()` or whatever the method could be called in case we'd implement file cache).
Anyway, this was something I put up together as a POC even before the #30  ticket was created. Now I only polished it up a bit so it's reviewable.
Not sure if this solution is the best fit for the purpose, nor I'm confident the code is following the spirit of go, so …

Use short-lived in-memory cache to cache previewed feeds

---

README.md
internal/commands/main.go
internal/commands/tui.go
internal/config/main.go
internal/rss/main.go

allows adding of custom name to feeds in the config file. This will be
prefixed to the title in the end result.
<index>: [feedname]: <title>
Having it as a config option for each feed is more flexible and there
wasn't a consistent way to get it from the RSS feeds themselves

add feed names to config

---

internal/store/store.go

The "Toggle read" functionality marked items as read, but never as unread.

fix: toggle read

---

cmd/nom/main.go
go.mod
internal/commands/commands.go
internal/commands/tui.go
internal/config/config_test.go
internal/rss/rss.go
internal/rss/rss_test.go

fixes issue with go install not pulling latest version and allows for bsd port
fixes #54, #51

fix: make module v2

---

internal/commands/commands.go
internal/commands/tui.go
internal/config/config.go
internal/store/store.go

allows favouriting, showing all favourites and do not delete favourite items when cleaning up old feeds
closes #5

feat: add ability to favourite items

---

README.md
internal/commands/commands.go
internal/commands/tui.go
internal/config/config.go

allows custom commands to open links bsed on a regex
closes #53

feat: add openers for links

---

.gitignore
internal/commands/tui.go

moves padding to the app instead of title, stops the jumping around when changing modes e.g. showing the filter.

chore: add nom gitignore, padding on app

---

Dockerfile
go.mod
go.sum

I'm not sure if there were things that used to be done implicitly, or what exactly has prompted this issue, but I've found that a fresh build and run of the binary with Docker results in an environment that doesn't have `gcc` or `alpine-sdk` installed, and requires a couple build flags passed in, namely `CGO_ENABLED=1` and `CGO_CFLAGS="-D_LARGEFILE64_SOURCE"`. The last flag can be ignored if we update `go-sqlite3`, which seems like the right move.
All in all, I can say for sure that adding those packages and flags into the Dockerfile seems to solve all related issues completely. If you have any insights, please do let me know.
A slight alternative would be to continue with the update to sqlite3, but pass in CGO_ENABLED into the `Makefile`'s `build` section, but this seems more well-scoped …

Fix the Dockerfile's environment for CGO

---

internal/commands/key.go
internal/commands/tui.go

Fixes #64.
- Added `key.go` to handle keybindings with `bubbles/key`.
- Transitioned `tui.go` to use keybindings defined in `key.go`.
- Added `model.help` to handle help messages.
- Overrode the `list.KeyMap.CancelWhileFiltering` to `q`.
- Added `viewport` full help menu, extracted help keys to `key.go`.
- Changed `g` viewport keybinding to be consistent with `list`.
- Extracted `list` overrides into `key.go#SetOverrides`.

Transitioned codebase to bubbles/key keybinds

---

internal/commands/tui.go

it now checks whether the returned item is nil and prints "No links selected."
How to recreate the issue:
add a RSS url so we would have bunch of articles in the main TUI.
then toggle read(m) all of them so no article would remain, then by clicking o to open links, the program would crash as a nil dereference and usage happens.

fix: crashing from opening links when a nil item is returned

---

internal/commands/commands.go
internal/commands/tui.go

Had to update two places, `commands.go` so it fetches correctly on first run, and `tui.go` so it doesn't fetch all articles when there's a feed flag passed, only the previews.

Fixed fetches so they are consistent with previews

---

.gitignore
cmd/nom/main.go
internal/commands/commands.go
internal/config/config.go
internal/config/config_test.go
internal/rss/rss.go

reddits bot detection is no longer happy with using GODEBUG to disabel http2, seems to be happy with enabled and setting proper UA
related #77

fix: remove GODEBUG v2 and set UA

---

README.md
internal/commands/commands.go
internal/commands/key.go
internal/commands/tui.go
internal/config/config.go
internal/config/config_test.go
internal/store/store.go

adds E keybind to open config in $EDITOR or $NOMEDITOR
fixed config not being a pointer
related https://github.com/guyfedwards/nom/issues/1

feat: add E to edit config in nom

---

internal/commands/commands.go
internal/commands/feeds.go
internal/config/config.go
internal/config/http.go
internal/rss/rss.go

I kept receiving 403s from https://fs.blog/feed/ . It turns out that it's probably because cloudflare blocks you unless you specify a minimum TLS version.
TLS 1.3 might be too high, but it solved my problem.

specify minimum tls version

---

README.md
cmd/nom/main.go
internal/commands/commands.go
internal/commands/list.go

Partial for #101
I couldn't wrap my head around on how to hook into TUI correctly to fetch but also dynamically update list like `r` key does but from some event or go routine.
- Added `config` for convenience.
- Added a timestamp for refreshed status.
If timestamp is welcomed I'm also open to making it configurable from config for those who prefer something other than `YYYY-MM-DD hh:mm:ss`.

feat: refresh without tui interval functionality

---

internal/commands/feeds.go
internal/commands/key.go
internal/commands/list.go
internal/config/config.go
internal/config/config_test.go
internal/constants/store.go
internal/store/store.go
internal/test/data/config_fixture.yml

Starting this as draft in case there's a different implementation approach desired for #74 and allowing me to self-review again at some point.
- Added `s` key for sorting in TUI on list view. Help is only on Full.
- Decided to use config for ordering and set default as `asc` to keep same behavior as "normal" scan. This could maybe use some discussion if order of items in table is a valid/desired sorting option?
- Left out sorting for preview feeds functionality.
Utilized store pointer to toggle sort and then reusing `GetAllFeeds` to apply other config like show favorites/read by default.

feat: add sorting order to config and abiity to change order in TUI

---

internal/commands/commands.go
internal/commands/key.go
internal/commands/list.go
internal/commands/tui.go
internal/commands/viewport.go
internal/config/config.go

Show Read Version
I didn't notice this first time around but page down is actually `f/pgdn` page down. Switched to F as it's annoying if you favorite and it moves your screen.

fix: indexing and autoread retoggle

---

internal/commands/filter.go

Resolves: https://github.com/guyfedwards/nom/issues/119
This PR implements fuzzy searching on tags.
I removed the old `FilterBy` function and introduced a function to filter on the feed names. Also moved the condition of `FilterBy` outside of the function.
If a feed name matches multiple feed name filters in the fuzzy search, then only the best match will be returned. This is to prevent duplicates in the output.

add: Filter feed names with fuzzy search

---

README.md
cmd/nom/main.go
internal/commands/commands.go

I often add name after adding a feed, so desided to made it easier

feat: add name as a second param while adding feed

---

README.md
cmd/nom/main.go
internal/config/config.go
internal/store/store.go

I have never touched go before and just took a stab at this change myself so as not to just be making requests for something I might be able to contribute instead. As it stands, the feature request outlined below is working as desired with this change, but if I overlooked some obvious extra things that needed to be included, now you know why. Either way, thanks for the nice software package.
When using multiple config files to be able to run nom under multiple 'profiles', of sorts, a user can separate different types of feeds effectively, but the hard-coded sqlite store file becomes a problem as each profile stomps over the others. There are various paths to solve this, but I figured the easiest solution would be to allow each alternate config file to define its own sqlite store to use. …

feat: allow data store config

---

README.md
internal/commands/commands.go
internal/commands/list.go
internal/commands/tui.go
internal/config/config.go

add refreshinterval config option to set the background interval refresh in minutes calls fetchAllFeeds in background and sends a status message
close #101

feat: add refreshinterval for bg refresh

---

.gitignore

To exclude a file at the root of a git repository, we need to write:
/nom
Instead of:
./nom
This was causing the generated `nom` binary to show up as an untracked file
in the output of `git status`.

fix: Correct .gitignore syntax

---

cmd/nom/main.go
internal/config/config.go
internal/config/config_test.go

The config handling code was erroneously including the path separator in arguments to `filepath.Join`, like this:
configFile := filepath.Join(configDir, "/config.yml")
When running nom against a config file in the current directory:
nom --config-path config.yml
This would result in `configDir` equal to `""`, and `configFile` would get set to `/config.yml`. This commit updates the path handling code to correctly use `filepath.Join`. It also replaces string splitting on paths with `filepath.Split`.
We also add a `-c` short option for setting the configuration path:
nom -c config.yml

fix: Fix config path handling
